app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@AppBundle/Controller/API'
    prefix: /api

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }


